# Generated by Django 3.2.3 on 2021-06-08 08:47

import contents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('short_description', models.CharField(max_length=128)),
                ('image', models.ImageField(upload_to=contents.models.upload_location)),
            ],
        ),
    ]
